### ISSUE TITLE
Feat(DefinitionList)

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/components#177]
Please add an editable property or the ability to add your own controls:

![image](https://github.com/gravity-ui/components/assets/104302104/73803810-93ce-4d9b-b316-3d388f62f555)

**Comment by korvin89** [comment]
@Raubzeug Hi! Would you triage this one?

**Comment by Raubzeug** [comment]
@lu-perfect Hi! If I understood you correctly, such an ability is already supported in the `DefinitionList`: `content` property is `ReactNode`, so you can pass whatever you need.

**Comment by lu-perfect** [comment]
btw, you are already using this in production, and given that the icon here is quite strange, I assume that the situation I was talking about arose here - the developer had to come up with how the basic functionality should look and work. 

![telegram-cloud-photo-size-2-5231018142598289467-y](https://github.com/gravity-ui/components/assets/104302104/d9146a51-e166-4051-9716-112ad023cd4a)

**Comment by Raubzeug** [comment]
@lu-perfect
We discussed this issue deeper and it seems that `copy` is essential action, that most of users will want to use in `DefinitionList`, but other actions like `edit` or maybe `click`, or `go outside link` etc. are much rarer cases.
And if we decide to implement all of this cases, component will grow complicated and hard to maintain, not to say that all of this cases has lots of ways to implement, and every user has his own best one.
Every component in every library has it's own level of abstraction. We provide api that allows to handle most of user's needs (we hope so), but sometimes it takes a little harder, I admit.
In you case I suggest to make `content` a separate component, so you won't need lots of copy-paste.

Btw, the example, you showed is an old component, even not from this library. I hope guys will move to a fresh one, and it will look much nicer.
